#
# Defines environment variables.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#
ZDOTDIR=/Users/riyer/local/dotfiles/shell
ZPREZTO=prezto

# Ensure that a non-login, non-interactive shell has a defined environment.
if [[ "$SHLVL" -eq 1 && ! -o LOGIN && -s "${ZDOTDIR:-$HOME}/$ZPREZTO/runcoms/zprofile" ]]; then
    source "${ZDOTDIR:-$HOME}/$ZPREZTO/runcoms/zprofile"
fi

