#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/$ZPREZTO/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/$ZPREZTO/init.zsh"
fi

# Customize to your needs...

if [[ -s "${ZDOTDIR:-$HOME}/zsh_custom/.zshrc.local" ]]; then
  source "${ZDOTDIR:-$HOME}/zsh_custom/.zshrc.local"
fi

test -e ${HOME}/.iterm2_shell_integration.zsh && source ${HOME}/.iterm2_shell_integration.zsh

# The next line updates PATH for the Google Cloud SDK.
if [ -f '/Users/riyer/Work/google-cloud-sdk/path.zsh.inc' ]; then source '/Users/riyer/Work/google-cloud-sdk/path.zsh.inc'; fi

# The next line enables shell command completion for gcloud.
if [ -f '/Users/riyer/Work/google-cloud-sdk/completion.zsh.inc' ]; then source '/Users/riyer/Work/google-cloud-sdk/completion.zsh.inc'; fi
