#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/$ZPREZTO/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/$ZPREZTO/init.zsh"
fi

# Customize to your needs...

if [[ -s "${ZDOTDIR:-$HOME}/zsh_custom/.zshrc.local" ]]; then
  source "${ZDOTDIR:-$HOME}/zsh_custom/.zshrc.local"
fi

test -e ${HOME}/.iterm2_shell_integration.zsh && source ${HOME}/.iterm2_shell_integration.zsh
